# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
install: true
before_script:
  - gradle wrapper --gradle-version=4.10.3
script:
  - ./gradlew clean build

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
